project:
  type: website
  render:
    - "*.qmd"
    - "!dontgit/"
    - "!cv"
    
website:
  title: "Manuel Reif"
  site-url: https://manuelreif.at
  description: "Manuels Website und Blog zu höchtpersönlichen Data Science Themen"
  google-analytics: "G-TV2KQ9KDW0"
  navbar:
    search: true
    logo: logo1.png
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: pkgs.qmd
        text: R-Packages
      - href: blog.qmd
        text: Blog {{< fa blog >}}
    right: 
      - href: impressum.qmd
        text: Impressum 
      - icon: rss
        href: blog.xml
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

highlight-style: monokai

execute: 
  freeze: auto

